$(document).ready(function(){
    $('.sidebar-btn').click(function(){
        $('.sidebar').toggleClass('show')
        $('.sidebar-btn').toggleClass('toggle')
    });
})
$(document).ready(function(){
    $('#sidebar-btn').click(function(){
        $('.sidebar').toggleClass('show')
        $('#sidebar-btn').toggleClass('toggle')
    });
})
